@uri = http://localhost:{{ $dotenv PORT }}

#csurf - cookie avec une jwt valide 1 an
@cookie_csurf = token_data=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InRva2VuIjoiZXlKamIyNTBaVzUwSWpvaWIzUlRTR3RRV0d4aWRHOXpXR1UzV1d0WWVVcFhUSE5IYkhCWVRtOW5WV1JRVFdoUGNtaFJUemhXYUZkV1JHMWlVWHBHU1ZVdlJtd3ljRzRyYUZVdmVYQm9TVVpQUms0M1UzWnlMMkZNY1RoSFdrZzFkVUZwWlV0RGVVeHpLMUpqYlN0MlZYUmFXVm9yTWpOeU5qUkpPVXhDWTBOcllVUk1hMGhXUzNScFQzRWlmUT09In0sImlhdCI6MTY1NjUyMzM2OSwiZXhwIjoxNjg2NzYzMzY5LCJpc3MiOiJtaXN0eWNsaWMiLCJzdWIiOiJjc3VyZl90b2tlbiIsImp0aSI6IjYyOTM3MjQxLWJmNTEtNDUzNC04MmMwLWUwYTBkNDVkZjcyOCJ9.1HbGbg9IPG8tOLrolULu3QNwcM3_4RIPCcCP0PExQeA

#cookie auth professionnel valide 1 an
@cookie_auth_pro = authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InJvbGVJZCI6M30sImlhdCI6MTY1NjUyMzM2OSwiZXhwIjoxNjg2NzYzMzY5LCJpc3MiOiJtaXN0eWNsaWMiLCJzdWIiOiJhdXRob3JpemF0aW9uIiwianRpIjoiYzcxMWViYTAtODc1Zi00M2UxLWE0MGMtNWEyZjEyMDFiNzFmIn0.u3dUpCVxzCnuGfMGOK56JAsg5C3YgAu99O8fsfcMtyk

#cookie auth utilisateur valide 1 an
@cookie_auth_user = authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InJvbGVJZCI6MX0sImlhdCI6MTY1NjUyMzM2OSwiZXhwIjoxNjg2NzYzMzY5LCJpc3MiOiJtaXN0eWNsaWMiLCJzdWIiOiJhdXRob3JpemF0aW9uIiwianRpIjoiMjFkZmI1OWQtZjdjOC00NmYxLWFmMTktZDg2ZDgwYzk5MGE1In0.hpm_Txix1BNbIMg9p21Sjzcf-HOfgkUSzXQTSDc1tss

#cookie auth admin valide 1 an
@cookie_auth_admin = authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InJvbGVJZCI6NH0sImlhdCI6MTY1NjUyMzM2OSwiZXhwIjoxNjg2NzYzMzY5LCJpc3MiOiJtaXN0eWNsaWMiLCJzdWIiOiJhdXRob3JpemF0aW9uIiwianRpIjoiMGM1Njc3Y2YtYjVkNS00YmI3LWJmM2YtMDU2MTIxN2E3ZDU4In0.xACoJIGW798Tya07jOlEF8DAJp0i71TXY2eNaBopkh0

#token associé a ce jwt
@token = "eyJjb250ZW50Ijoiem1ibC9QUkF6N2hUV0JPTm5kaTQyTmhFdENSZEEzK2RTcE9HUGYrc0dWVHZOQ2hGZ3FpMWVNTTNZc2JRN3NyZSJ9"

@wrong_token = "eyJjb250ZW50Ijoiem1ibC9QUkF6N2hUV0JPTm5kaTQyTmhFdENSZEEzK2RTcE9HUGYrc0dWVHZOQ2hGZ3FpMWVNTTNZc2JRN3NyZSJ8"

### Ajout d'une offre
POST {{uri}}/api/offers/
Cookie: {{cookie_csurf}}
Cookie: {{cookie_auth_pro}}
Content-Type: application/json

{
    "token": {{token}},    
    "name": "modifi",
    "presentation": "pour l'achat de 2 roses, vous bénificié d'un remboursement immédiat de 0.50€",
    "globalRefund": "499",
    "individualRefund": "0.50",
    "imageName": "fleur.jpg",
    "userId": "4",
    "storeId": "2",
    "cityId": "2",
    "conditions": [1,2,3]
}

### modification d'un offre
PATCH {{uri}}/api/offers/1
Cookie: {{cookie_csurf}}
Cookie: {{cookie_auth_admin}}
Content-Type: application/json

{
    "token": {{token}},    
    "name": "gfdg",
    "presentation": "pour l'achat de 2 roses, vous bénificié d'un remboursement immédiat de 0.50€",    
    "imageName": "test.jpg",
    "userId": "4",
    "storeId": "2",
    "conditions": [2,1,6]
}

### récupération d'une offre
GET {{uri}}/api/offers/1

### récupération de toutes les offres
GET {{uri}}/api/offers

### récupération des offres par ville
GET {{uri}}/api/offers/by-city/10

### récupération des offres par store
GET {{uri}}/api/offers/by-store/5

### récupération de toutes les offres par un professionel
GET {{uri}}/api/offers/token/{{token}}/professional/4
Cookie: {{cookie_csurf}}
Cookie: {{cookie_auth_admin}}

### récupération offres d'un commerce par un professionnel Id
GET {{uri}}/api/offers/token/{{token}}/professional/2/store/1
Cookie: {{cookie_csurf}}
Cookie: {{cookie_auth_pro}}

### récupération des codes de remboursement par offerId
GET {{uri}}/api/offers/get-tokens-by-offer/token/{{token}}/professional/4/store/2/offer/1
Cookie: {{cookie_csurf}}
Cookie: {{cookie_auth_admin}}

###suppression d'une offre
DELETE {{uri}}/api/offers/1
Cookie: {{cookie_csurf}}
Cookie: {{cookie_auth_admin}}
Content-Type: application/json

{
    "token": {{token}},
    "userId": "4",
    "storeId": "2" 
}

### client souscri à une offre - génration d'un token
GET  {{uri}}/api/offers/generate-token-by-offer/token/{{token}}/user/1/store/2/offer/3
Cookie: {{cookie_csurf}}
Cookie: {{cookie_auth_pro}}

### validation d'un rembourssement
POST {{uri}}/api/offers/refund/hciti
Cookie: {{cookie_csurf}}
Cookie: {{cookie_auth_pro}}
Content-Type: application/json

{
    "token": {{token}},
    "storeId": "2" 
}